// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfa0Wo-yHcsGxw_iMjeopVxc5SUxhdjaQ',
    appId: '1:952671342269:web:8a4a3c833fe4b397df31d4',
    messagingSenderId: '952671342269',
    projectId: 'sudukbackx6',
    authDomain: 'sudukbackx6.firebaseapp.com',
    storageBucket: 'sudukbackx6.appspot.com',
    measurementId: 'G-QGP9NPKD9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP4rYc4zC8NYS-JjVVlbDqKZJNF0iOjRk',
    appId: '1:952671342269:android:b1d875d67fe2b045df31d4',
    messagingSenderId: '952671342269',
    projectId: 'sudukbackx6',
    storageBucket: 'sudukbackx6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXXC0w1QjZGE2vwVjDoTJqRCH6ifufVrA',
    appId: '1:952671342269:ios:e5e74d3106842777df31d4',
    messagingSenderId: '952671342269',
    projectId: 'sudukbackx6',
    storageBucket: 'sudukbackx6.appspot.com',
    iosBundleId: 'com.example.guncagaca',
  );
}
