// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUUAEeve_MnCsuw-4iKe3OTox9nH0Ak1Y',
    appId: '1:494149121366:web:b8c7834f324613319312f7',
    messagingSenderId: '494149121366',
    projectId: 'guncagaca',
    authDomain: 'guncagaca.firebaseapp.com',
    storageBucket: 'guncagaca.appspot.com',
    measurementId: 'G-KV3X1BDND5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxyG9uF1YkOS3dKueXhXzbjIKE9nmZuYc',
    appId: '1:494149121366:android:a3bbc5d7bfd9d6299312f7',
    messagingSenderId: '494149121366',
    projectId: 'guncagaca',
    storageBucket: 'guncagaca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmzRx_RyO2yd6ff2ab4WijW3t_cokuIsM',
    appId: '1:494149121366:ios:85fd3ce137d24cf29312f7',
    messagingSenderId: '494149121366',
    projectId: 'guncagaca',
    storageBucket: 'guncagaca.appspot.com',
    iosBundleId: 'com.example.guncagaca',
  );
}
