spring:
  application:
    name: order
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.hibernate.type: trace