spring:
  application:
    name: gateway
  profiles:
    active: dev
  config:
    import: optional:configserver:http://k9d102.p.ssafy.io:8888


management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.hibernate.type: trace
