server:
  port: 8081

spring:
  application:
    name: member-service
  datasource:
    url: jdbc:mysql://15.165.116.170:3306/member_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: coco
    password: d102d102

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1
    password: 'local'

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true