spring:
  application:
    name: pay
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.hibernate.type: trace