spring:
  application:
    name: eunjin-test      # ?????? ?? = Github ??????? ???? ?? ?????? ??
  profiles:
    active: local     # ?????? ?? = local, dev
  config:
    import: optional:configserver:http://localhost:8088 # import:optional:configserver?? -> Spring cloud config server ??
server:
  port: 9001     # Spring Cloud Config Client ??

# ????? ???? Actuator ??
management:
  endpoints:
    web:
      exposure:
        include: "*"
