spring:
  application:
    name: admin
  profiles:
    active: dev
  config:
    import: optional:configserver:http://k9d102.p.ssafy.io:8888

server:
  port: 9999

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.hibernate.type: trace

