spring:
  application:
    name: store
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.hibernate.type: trace
        include: "*"