spring:
  application:
    name: owner
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8088
server:
  port: 8086
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.hibernate.type: tracegi